// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BlogEngine.Infrastructure.Migrations
{
    [DbContext(typeof(BlogEngineContext))]
    internal class BlogEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BlogEngine.Domain.Entities.Article", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Content")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreateTime")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdateTime")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Articles");
            });

            modelBuilder.Entity("BlogEngine.Domain.Entities.Comment", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("ArticleId")
                    .HasColumnType("TEXT");

                b.Property<string>("Author")
                    .HasColumnType("TEXT");

                b.Property<string>("Content")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreateTime")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdateTime")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ArticleId");

                b.ToTable("Comments");
            });

            modelBuilder.Entity("BlogEngine.Domain.Entities.Comment", b =>
            {
                b.HasOne("BlogEngine.Domain.Entities.Article", "Article")
                    .WithMany("Comments")
                    .HasForeignKey("ArticleId");
            });
#pragma warning restore 612, 618
        }
    }
}