// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BlogEngine.Articles.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(ArticlesContext))]
    internal class ArticlesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogEngine.Articles.Domain.Entities.Article", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Content")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreateTime")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("getutcdate()");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdateTime")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("getutcdate()");

                b.HasKey("Id");

                b.HasIndex("CreateTime");

                b.HasIndex("UpdateTime");

                b.ToTable("Articles");
            });

            modelBuilder.Entity("BlogEngine.Articles.Domain.Entities.Comment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ArticleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Author")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Content")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreateTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdateTime")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ArticleId");

                b.ToTable("Comment");
            });

            modelBuilder.Entity("BlogEngine.Articles.Domain.Entities.Article", b =>
            {
                b.OwnsMany("BlogEngine.Domain.Common.ValueObjects.HashTag", "HashTags", b1 =>
                {
                    b1.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b1.HasKey("ArticleId", "Id");

                    b1.ToTable("HashTag");

                    b1.WithOwner()
                        .HasForeignKey("ArticleId");
                });

                b.Navigation("HashTags");
            });

            modelBuilder.Entity("BlogEngine.Articles.Domain.Entities.Comment", b =>
            {
                b.HasOne("BlogEngine.Articles.Domain.Entities.Article", "Article")
                    .WithMany("Comments")
                    .HasForeignKey("ArticleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Article");
            });

            modelBuilder.Entity("BlogEngine.Articles.Domain.Entities.Article", b => { b.Navigation("Comments"); });
#pragma warning restore 612, 618
        }
    }
}